// ─── DỮ LIỆU SẢN PHẨM ────────────────────────
const PRODUCTS = [
    // ── GIÀY ──
    {
        id: 1,
        name: "Nike Air Max 270 React",
        brand: "nike",
        category: "giay",
        price: 2_890_000,
        originalPrice: 3_500_000,
        tags: ["hot", "bestseller"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 5,
        reviews: 128,
        image: "https://cdn.vuahanghieu.com/unsafe/0x900/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2024/03/giay-the-thao-nike-air-max-270-react-pink-grey-orange-shoes-ct1834-100-phoi-mau-size-37-5-65fe58288ae5e-23032024111848.jpg",
        desc: "Đệm Air Max 270 mang lại độ đàn hồi tối ưu cho mỗi bước chạy. Thiết kế hiện đại, phù hợp cả tập luyện lẫn thời trang đường phố.",
    },
    {
        id: 2,
        name: "Adidas Ultraboost 22",
        brand: "adidas",
        category: "giay",
        price: 3_200_000,
        originalPrice: 4_000_000,
        tags: ["hot", "sale"],
        sizes: [39, 40, 41, 42, 43, 44],
        stars: 5,
        reviews: 95,
        image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500&q=80",
        desc: "Công nghệ Boost mang lại năng lượng hoàn trả tối đa. Đế ngoài Continental™ bám đường xuất sắc trong mọi điều kiện thời tiết.",
    },
    {
        id: 3,
        name: "Giày thể thao CA Match",
        brand: "puma",
        category: "giay",
        price: 1_840_000,
        originalPrice: 2_300_000,
        tags: ["new", "sale"],
        sizes: [38, 39, 40, 41, 42],
        stars: 4,
        reviews: 67,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/400779/01/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-th%E1%BB%83-thao-CA-Match",
        desc: "Bước đi trên đôi giày đầy thời thượng lấy cảm hứng từ môn quần vợt. Thân trên bằng da tổng hợp, logo PUMA mang tính biểu tượng và chi tiết kim loại nổi bật, đôi giày mang đến dáng vẻ thể thao tinh giản, dễ dàng kết hợp với mọi trang phục. Lựa chọn hoàn hảo cho những ai yêu thích phong cách thoải mái và sành điệu.",
    },
    {
        id: 4,
        name: "Converse Chuck Taylor All Star",
        brand: "converse",
        category: "giay",
        price: 1_290_000,
        originalPrice: null,
        tags: ["bestseller"],
        sizes: [36, 37, 38, 39, 40, 41, 42],
        stars: 5,
        reviews: 312,
        image: "https://product.hstatic.net/200000265619/product/121186-1_d83cf53a24ef440ea44f5c28778298a0_1024x1024.jpg",
        desc: "Huyền thoại canvas bất diệt từ 1917. Cổ cao classic với đế cao su vulcanized bền bỉ theo thời gian.",
    },
    {
        id: 5,
        name: "New Balance 574 Core",
        brand: "new-balance",
        category: "giay",
        price: 2_150_000,
        originalPrice: 2_600_000,
        tags: ["new"],
        sizes: [39, 40, 41, 42, 43, 44],
        stars: 4,
        reviews: 84,
        image: "https://d3vfig6e0r0snz.cloudfront.net/rcYjnYuenaTH5vyDF/images/products/2c0bad21aa7252be35326fa10632d802.webp",
        desc: "Đôi giày cổ điển với công nghệ ENCAP mang lại sự thoải mái suốt cả ngày. Chất liệu suede & mesh cao cấp.",
    },
    {
        id: 6,
        name: "VANS CHECKERBOARD SLIP-ON CLASSIC BLACK/OFF WHITE",
        brand: "vans",
        category: "giay",
        price: 1_305_000,
        originalPrice: 1_450_000,
        tags: ["sale", "hot"],
        sizes: [36, 37, 38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 156,
        image: "https://bizweb.dktcdn.net/thumb/1024x1024/100/140/774/products/vans-slip-on-checkerboard-black-off-white-vn000eyebww-1.png",
        desc: "Bắt đầu trở nên nổi tiếng khi được Sean Penn sử dụng trong bộ phim Fast Times vào năm 1982 và từ phong trào trở thành một phong cách huyền thoại không hề lỗi thời và luôn nằm trong mục 'Best Seller' của VANS cho tới thời điểm hiện tại.",
    },
    {
        id: 7,
        name: "Nike Air Force 1 '07",
        brand: "nike",
        category: "giay",
        price: 2_500_000,
        originalPrice: null,
        tags: ["bestseller", "hot"],
        sizes: [38, 39, 40, 41, 42, 43, 44],
        stars: 5,
        reviews: 247,
        image: "https://i.ebayimg.com/images/g/FE0AAOSwhZ9jo3Ey/s-l1600.webp",
        desc: "Biểu tượng bóng rổ kể từ 1982, nay trở thành cột mốc của văn hóa streetwear toàn cầu. Đế Air bất hủ.",
    },
    {
        id: 8,
        name: "Adidas Stan Smith",
        brand: "adidas",
        category: "giay",
        price: 1_890_000,
        originalPrice: 2_200_000,
        tags: ["new", "sale"],
        sizes: [37, 38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 193,
        image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500&q=80",
        desc: "Giày tennis trắng tinh khôi với điểm nhấn xanh lá. Thiết kế tối giản trường tồn qua hơn 50 năm lịch sử.",
    },

    // ── DÉP ──
    {
        id: 9,
        name: "Adidas Adilette Aqua",
        brand: "adidas",
        category: "dep",
        price: 590_000,
        originalPrice: 750_000,
        tags: ["bestseller", "sale"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 220,
        image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&q=80",
        desc: "Dép quai ngang nhẹ nhàng với đế EVA siêu êm. Chất liệu nhanh khô, lý tưởng cho hồ bơi và biển.",
    },
    {
        id: 10,
        name: "Nike Benassi JDI",
        brand: "nike",
        category: "dep",
        price: 650_000,
        originalPrice: null,
        tags: ["hot"],
        sizes: [37, 38, 39, 40, 41, 42],
        stars: 4,
        reviews: 178,
        image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&q=80",
        desc: "Dép slide phong cách với quai dệt thêu logo Swoosh. Đế Phylon nhẹ và đàn hồi tốt cho mọi hoạt động.",
    },
    {
        id: 11,
        name: "Dép quai ngang Cool Cat 2.0 V FS",
        brand: "puma",
        category: "dep",
        price: 700_000,
        tags: ["new", "sale"],
        sizes: [36, 37, 38, 39, 40, 41, 42],
        stars: 3,
        reviews: 54,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/390961/07/sv01/fnd/VNM/fmt/png/D%C3%A9p-quai-ngang-Cool-Cat-2.0-V-FShttps://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/390961/07/sv04/fnd/VNM/fmt/png/D%C3%A9p-quai-ngang-Cool-Cat-2.0-V-FS",
        desc: "Chất từ cái tên, chất từ trong bản chất, mẫu dép này đã trở lại và lợi hại hơn bao giờ hết. Dép nhẹ, sành điệu và sẵn sàng đón chào mùa hè, được hoàn thiện với chi tiết nhãn hiệu PUMA Formstrip cổ điển.",
    },
    {
        id: 12,
        name: "Under Armour Ignite Select",
        brand: "under-armour",
        category: "dep",
        price: 720_000,
        originalPrice: 900_000,
        tags: ["new"],
        sizes: [39, 40, 41, 42, 43, 44],
        stars: 4,
        reviews: 41,
        image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&q=80",
        desc: "Công nghệ OrthoLite® mang lại sự thoải mái vượt trội sau các buổi tập luyện cường độ cao.",
    },

    // ── QUẦN ÁO ──
    {
        id: 13,
        name: "Nike Dri-FIT ADV Run Division",
        brand: "nike",
        category: "quan-ao",
        price: 1_290_000,
        originalPrice: 1_600_000,
        tags: ["hot", "sale"],
        sizes: [38, 40, 42, 44],
        stars: 5,
        reviews: 88,
        image: "https://i.ebayimg.com/images/g/Lm0AAeSwETNpTpqP/s-l1600.webp",
        desc: "Áo chạy bộ với công nghệ Dri-FIT ADV hút ẩm cực mạnh. Cấu trúc lưới thoáng khí tối ưu hóa cho tốc độ.",
    },
    {
        id: 14,
        name: "Adidas Tiro 23 Track Jacket",
        brand: "adidas",
        category: "quan-ao",
        price: 1_150_000,
        originalPrice: null,
        tags: ["bestseller", "new"],
        sizes: [38, 40, 42, 44, 46],
        stars: 4,
        reviews: 112,
        image: "https://d3vfig6e0r0snz.cloudfront.net/rcYjnYuenaTH5vyDF/images/products/8aa06b8ba07e12b3e7810ff740287930.webp",
        desc: "Áo khoác track jacket biểu tượng của Adidas. Vải polyester tái chế 100%, góp phần bảo vệ môi trường.",
    },
    {
        id: 15,
        name: "Puma Evostripe Full-Zip Hoodie",
        brand: "puma",
        category: "quan-ao",
        price: 990_000,
        originalPrice: 1_300_000,
        tags: ["sale"],
        sizes: [38, 40, 42, 44],
        stars: 4,
        reviews: 63,
        image: "https://thoitrangbigsize.vn/wp-content/uploads/2024/07/BS2769.jpg",
        desc: "Hoodie khóa kéo toàn thân từ chất liệu fleece mềm mại. Phần ôm vừa vặn, hoàn hảo cho tập gym hay dạo phố.",
    },
    {
        id: 16,
        name: "Under Armour Challenger Pro Pants",
        brand: "under-armour",
        category: "quan-ao",
        price: 850_000,
        originalPrice: 1_100_000,
        tags: ["hot", "sale"],
        sizes: [38, 40, 42, 44, 46],
        stars: 4,
        reviews: 77,
        image: "https://cdn.hstatic.net/products/200000940675/20_d1c513893b7041f18787922784485d4d_1024x1024.jpg",
        desc: "Quần track pants với vải woven chắn gió nhẹ. Thiết kế ergonomic theo chuyển động tự nhiên của cơ thể.",
    },
    {
        id: 17,
        name: "Reebok Identity Fleece Shorts",
        brand: "reebok",
        category: "quan-ao",
        price: 650_000,
        originalPrice: null,
        tags: ["new"],
        sizes: [38, 40, 42, 44],
        stars: 3,
        reviews: 29,
        image: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=500&q=80",
        desc: "Quần short fleece unisex với logo Reebok Vector nổi bật. Lưng thun rộng thoải mái cho mọi hoạt động.",
    },

    // ── PHỤ KIỆN ──
    {
        id: 18,
        name: "Nike Heritage86 Cap",
        brand: "nike",
        category: "phu-kien",
        price: 450_000,
        originalPrice: 590_000,
        tags: ["bestseller", "sale"],
        sizes: [40],
        stars: 4,
        reviews: 145,
        image: "https://bizweb.dktcdn.net/thumb/1024x1024/100/438/626/products/4275a4f1-0428-4e33-8fee-30d2b0cb24a0.jpg?v=1695712796733",
        desc: "Mũ lưỡi trai 6 mảnh với dây điều chỉnh phía sau. Vải Dri-FIT giữ đầu luôn mát khi vận động.",
    },
    {
        id: 19,
        name: "Adidas Running Water Bottle 750ml",
        brand: "adidas",
        category: "phu-kien",
        price: 320_000,
        originalPrice: null,
        tags: ["new"],
        sizes: [40],
        stars: 4,
        reviews: 58,
        image: "https://i.ebayimg.com/images/g/arQAAOSwfC1jWCm6/s-l1600.webp",
        desc: "Bình nước 750ml không chứa BPA với nắp flip-top tiện lợi. Giữ lạnh 12 giờ, giữ nóng 6 giờ.",
    },
    {
        id: 20,
        name: "Puma Training Gloves Pro",
        brand: "puma",
        category: "phu-kien",
        price: 380_000,
        originalPrice: 490_000,
        tags: ["hot", "sale"],
        sizes: [38, 40, 42],
        stars: 4,
        reviews: 37,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/042138/01/fnd/EEA/fmt/png/FUTURE-Pro-NC-Goalkeeper-Gloves-Unisex",
        desc: "Găng tay tập gym với lớp đệm gel bảo vệ lòng bàn tay. Dây quấn cổ tay hỗ trợ và ổn định khớp.",
    },
    {
        id: 21,
        name: "New Balance Sport Backpack 25L",
        brand: "new-balance",
        category: "phu-kien",
        price: 890_000,
        originalPrice: 1_100_000,
        tags: ["new", "hot"],
        sizes: [40],
        stars: 5,
        reviews: 66,
        image: "https://is4.fwrdassets.com/images/p/fw/45/TACF-MY71_V1.jpg",
        desc: "Balo thể thao 25L với ngăn riêng cho giày và quần áo ướt. Dây đeo có đệm thoáng khí, phân tán tải trọng.",
    },
    {
        id: 22,
        name: "Under Armour SportsMask",
        brand: "under-armour",
        category: "phu-kien",
        price: 290_000,
        originalPrice: 380_000,
        tags: ["sale"],
        sizes: [40],
        stars: 3,
        reviews: 24,
        image: "https://i.ebayimg.com/images/g/ntsAAOSwzGZnG1~h/s-l1600.webp",
        desc: "Khẩu trang thể thao với lớp lọc 3D thoáng khí. Vải UA Iso-Chill giúp mát hơn khi vận động mạnh.",
    },
    {
        id: 23,
        name: "Nike Dri-FIT Wristband Set",
        brand: "nike",
        category: "phu-kien",
        price: 190_000,
        originalPrice: null,
        tags: ["bestseller"],
        sizes: [40],
        stars: 4,
        reviews: 203,
        image: "https://i.ebayimg.com/images/g/rjoAAeSw9QBpCVuC/s-l1600.webp",
        desc: "Bộ băng cổ tay Dri-FIT thấm hút mồ hôi nhanh. Thiết kế co giãn, vừa vặn nhiều kích cỡ cổ tay.",
    },
    {
        id: 24,
        name: "Adidas Tiro League Shin Guards",
        brand: "adidas",
        category: "phu-kien",
        price: 240_000,
        originalPrice: 310_000,
        tags: ["new", "sale"],
        sizes: [38, 40, 42],
        stars: 4,
        reviews: 51,
        image: "https://i.ebayimg.com/images/g/~WYAAeSwprZpqinF/s-l1600.webp",
        desc: "Miếng bảo vệ ống chân bóng đá với lớp xốp EVA hấp thụ va đập. Nhẹ, ôm sát, không cản chuyển động.",
    },
    {
        id: 25,
        name: "Giày chạy địa hình Skyrocket Lite",
        brand: "puma",
        category: "giay",
        price: 870_000,
        originalPrice: 1_450_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/310781/11/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-ch%E1%BA%A1y-%C4%91%E1%BB%8Ba-h%C3%ACnh-Skyrocket-Lite",
        desc: "Giày chạy bộ địa hình Skyrocket Lite Trail, mẫu giày mới hoàn hảo cho mọi hành trình hằng ngày của bạn. Chúng tôi đã tích hợp hợp chất bọt nhẹ để mang lại sự thoải mái siêu nhẹ và cao su ProTread giúp tăng độ bám và độ bền. Với Skyrocket Lite Trail, bạn có thể làm được mọi thứ.",
    },
    {
        id: 25,
        name: "Giày Speedcat Ballet Suede Nữ",
        brand: "puma",
        category: "giay",
        price: 2_100_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/401287/22/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-Speedcat-Ballet-Suede-N%E1%BB%AF",
        desc: "Rewrite the classics với Speedcat Ballet – phiên bản mới của PUMA Speedcat. Lấy cảm hứng từ giày ballet cổ điển, Speedcat Ballet mang đến làn gió mới cho đôi giày từng là biểu tượng của văn hóa đua xe, với thiết kế slip-on thanh lịch. Với chi tiết Formstrip cắt cách điệu, dây co giãn và đế cao su lấy cảm hứng từ lốp xe, Speedcat Ballet chính là tuyên ngôn phong cách từ đường đua ra đường phố.",
    },
    {
        id: 26,
        name: "Giày chạy địa hình Fast-Trac NITRO™ 3 GTX dành cho nữ",
        brand: "puma",
        category: "giay",
        price: 2_220_000,
        originalPrice: 3_700_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4.5,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/379795/03/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-ch%E1%BA%A1y-%C4%91%E1%BB%8Ba-h%C3%ACnh-Fast-Trac-NITRO%E2%84%A2-3-GTX-d%C3%A0nh-cho-n%E1%BB%AF",
        desc: "Giới thiệu PUMA Fast-Trac 3, người bạn đồng hành hoàn hảo cho những bước chạy địa hình gọn nhẹ. Đôi giày sở hữu đế giữa NITROFOAM™ toàn chiều dài mang lại khả năng đệm êm và phản hồi nhanh, đinh cao su PUMAGRIP ATR 4mm giúp tăng độ bám không đối thủ, cùng phần cổ giày cuộn mềm mại tạo cảm giác thoải mái tối ưu. Phần thân giày trang bị công nghệ GORE-TEX®, giúp giữ chân bạn luôn khô ráo và dễ chịu dưới mọi điều kiện thời tiết. Chinh phục mọi địa hình tự tin cùng PUMA Fast-Trac NITRO™ 3.",
    },
    {
        id: 27,
        name: "Giày chạy địa hình Extend Lite",
        brand: "puma",
        category: "giay",
        price: 930_000,
        originalPrice: 1_550_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/379538/29/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-ch%E1%BA%A1y-%C4%91%E1%BB%8Ba-h%C3%ACnh-Extend-Lite",
        desc: "Extent Lite Trail đáp ứng nhu cầu chạy bộ trên các địa hình và đi bộ đường dài. Đế ngoài thiết kế có rãnh để tạo độ bám tối ưu trong khi phần trên được phân biệt bằng các chú thích của PUMA Trail và thiết kế PUMA Formstrip nổi tiếng",
    },
    {
        id: 28,
        name: "Giày Chạy Bộ Deviate NITRO™ 4 Nam",
        brand: "puma",
        category: "giay",
        price: 4_200_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/312123/26/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-Ch%E1%BA%A1y-B%E1%BB%99-Deviate-NITRO%E2%84%A2-4-Nam",
        desc: "Deviate 4 không chỉ nhanh – mà là quá nhanh. Nhẹ hơn 15g so với phiên bản trước, đôi giày hiệu suất cao này được tạo ra cho những runner không chấp nhận chậm lại. Trang bị công nghệ bọt đệm NITROFOAM™ cải tiến giúp hoàn trả năng lượng tốt hơn, thân giày bằng vải lưới kỹ thuật thoáng khí và tấm PWRPLATE bằng carbon tổng hợp, Deviate 4 mang đến lợi thế cần thiết để bạn bứt phá trong các buổi chạy giữ nhịp hoặc chinh phục ngày thi đấu. Chạy xa hơn. Chạy nhanh hơn.",
    },
    {
        id: 29,
        name: "Giày thể thao Palermo Lux dành cho nữ",
        brand: "puma",
        category: "giay",
        price: 2_000_000,
        originalPrice: 2_500_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/405493/02/sv01/fnd/VNM/fmt/png/Palermo-Lux-Sneakers-Women",
        desc: "Palermo Lux mang đến nguồn năng lượng tươi mới cho kiểu giày thể thao cổ điển. Với thiết kế đế cao được cải tiến táo bạo và những chi tiết nổi bật, đôi giày này mang đến phong cách thường ngày dễ dàng, tự tin và đầy cá tính.",
    },
    {
        id: 30,
        name: "Giày chạy bộ nam Electrify NITRO™ 4",
        brand: "puma",
        category: "giay",
        price: 1_500_00,
        originalPrice: 2_500_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/310789/02/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-ch%E1%BA%A1y-b%E1%BB%99-nam-Electrify-NITRO%E2%84%A2-4",
        desc: "Electrify NITRO™ 4 kết hợp hoàn hảo giữa NITROFOAM™ và PROFOAMLITE để mang lại cảm giác chạy linh hoạt và êm ái. Với phần trên bằng lưới thoáng khí và cao su PUMAGRIP cho độ bám ó một không hai, đôi giày này được thiết kế để đưa bạn tiến xa hơn từng km.",
    },
    {
        id: 31,
        name: "Mũ Lưỡi Trai Chạy Bộ Hằng Ngày",
        brand: "puma",
        category: "phu-kien",
        price: 520_000,
        originalPrice: 650_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/026998/04/fnd/VNM/fmt/png/M%C5%A9-L%C6%B0%E1%BB%A1i-Trai-Ch%E1%BA%A1y-B%E1%BB%99-H%E1%BA%B1ng-Ng%C3%A0y",
        desc: "Giữ nhịp chạy ổn định với chiếc mũ lưỡi trai không cấu trúc này. Vành mũ lưỡi trai cong sẵn kết hợp cùng khóa dây rút đàn hồi mang lại độ cố định chắc chắn nhưng vẫn thoải mái, trong khi công nghệ dryCELL giúp bạn luôn cảm thấy dễ chịu khi vận động. Dù là chạy trên đường hay dừng lại uống cà phê sau buổi tập, PUMA luôn đồng hành cùng bạn với phong cách ấn tượng.",
    },
    {
        id: 32,
        name: "Mũ lưỡi trai Metal Classics Gold",
        brand: "puma",
        category: "phu-kien",
        price: 450_000,
        originalPrice: 750_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/025363/04/fnd/VNM/fmt/png/M%C5%A9-l%C6%B0%E1%BB%A1i-trai-Metal-Classics-Gold",
        desc: "Chiếc mũ bóng chày sáu mảnh này là một sản phẩm cổ điển tuyệt vời. Nó có lưỡi trai được uốn cong trước và khóa kéo vừa vặn ở mặt sau bằng kẹp kim loại và có mấu kéo PUMA ở mặt sau.",
    },
    {
        id: 33,
        name: "Mũ lưỡi trai in họa tiết PUMA x RIPNDIP dành cho nam",
        brand: "puma",
        category: "phu-kien",
        price: 840_000,
        originalPrice: 1_200_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/026595/01/fnd/VNM/fmt/png/M%C5%A9-l%C6%B0%E1%BB%A1i-trai-in-h%E1%BB%8Da-ti%E1%BA%BFt-PUMA-x-RIPNDIP-d%C3%A0nh-cho-nam",
        desc: "Nermal đã trở lại và làm mọi thứ trở nên hoàn hảo. Chiếc mũ lưỡi trai này từ PUMA x RIPNDIP mang đến năng lượng trượt ván nổi loạn cho phong cách thường ngày của bạn, với họa tiết vui nhộn, điểm nhấn chức năng và phong cách đường phố.",
    },
    {
        id: 34,
        name: "Túi đeo chéo PUMA Sense 1.5L",
        brand: "puma",
        category: "phu-kien",
        price: 2_700_000,
        originalPrice: 1_450_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/092218/01/fnd/VNM/fmt/png/T%C3%BAi-%C4%91eo-ch%C3%A9o-PUMA-Sense-1.5L",
        desc: "Từ phong cách táo bạo và hợp xu hướng đến cổ điển và vượt thời gian, phụ kiện của chúng tôi đều sẵn sàng hoàn thiện vẻ ngoài của bạn. Chiếc túi đeo chéo này là một phần của bộ sưu tập PUMA Sense, gồm nhiều sản phẩm đa năng với các chi tiết chức năng và vẻ ngoài thể thao hiện đại.",
    },
    {
        id: 35,
        name: "Mũ Bucket Premium Essentials Script",
        brand: "puma",
        category: "phu-kien",
        price: 600_000,
        originalPrice: 750_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/026849/01/fnd/VNM/fmt/png/M%C5%A9-Bucket-Premium-Essentials-Script",
        desc: "Những món đồ thời trang đường phố được nâng tầm trong bộ sưu tập Premium Essentials của chúng tôi. Những tác phẩm sưu tầm này tái hiện di sản thể thao thông qua thiết kế tinh tế và ấn tượng. Mang đến phong cách vượt thời gian và sự thoải mái vượt trội, chắc chắn chúng sẽ trở thành món đồ chủ lực mới trong tủ đồ của bạn.",
    },
    {
        id: 36,
        name: "Mũ Lưỡi Trai Ferrari HYPERCAR Replica",
        brand: "puma",
        category: "phu-kien",
        price: 1_100_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/027197/01/fnd/VNM/fmt/png/M%C5%A9-L%C6%B0%E1%BB%A1i-Trai-Ferrari-HYPERCAR-Replica",
        desc: "Trông rất quen thuộc phải không? Đúng thế đấy. Chiếc mũ từng tung hoành trên đường đua – giờ đây là lúc bạn đội nó lên mình. Với loạt sản phẩm mang cảm hứng công nghệ gồm mũ lưỡi trai, mũ tròn và hơn thế nữa, bộ sưu tập Mô Phỏng SCUDERIA FERRARI HP của PUMA được tạo ra dành cho các Tifosi dám tăng tốc hết ga hướng tới tương lai và tự kiến tạo con đường của riêng mình. Chiếc mũ lưỡi trai này được lấy cảm hứng từ kiểu mũ mà các tay đua thường đội trong suốt mùa giải đua xe thử thách sự bền bỉ.",
    },
    {
        id: 37,
        name: "Giày thể thao RS-X PUMA x TNMT",
        brand: "puma",
        category: "giay",
        price: 2_100_000,
        originalPrice: 3_000_000,
        tags: ["new"],
        sizes: [38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 50,
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1000,h_1000/global/402373/01/sv01/fnd/VNM/fmt/png/Gi%C3%A0y-th%E1%BB%83-thao-RS-X-PUMA-x-TNMT",
        desc: "Hãy cùng đắm mình vào thế giới ngầm với lần kết hợp với TMNT của PUMA! Với phần đặt lỗ xỏ dây bằng da nứt, lớp phủ da lộn và dải Formstrip in 3D, đôi giày này chứa đầy các chi tiết ẩn và thiết kế táo bạo. Bộc lộ người hùng bên trong bạn qua từng bước chân.",
    },
    {
        id: 38,
        name: "VANS OLD SKOOL CLASSIC NAVY/WHITE",
        brand: "vans",
        category: "giay",
        price: 1_575_000,
        originalPrice: 1_750_000,
        tags: ["sale", "hot"],
        sizes: [36, 37, 38, 39, 40, 41, 42, 43],
        stars: 4,
        reviews: 156,
        image: "https://bizweb.dktcdn.net/thumb/1024x1024/100/140/774/products/vans-old-skool-classic-navy-white-vn000d3hnvy-2.jpg?v=1625922077960",
        desc: "VANS OLD SKOOL là phiên bản được fan hâm mộ của VANS ưa thích nhất bởi kiểu dáng đơn giản nhưng vẫn hợp thời trang. Với đế cao su độ bám tốt cùng thiết kế tối ưu cho môn trượt ván, BMX và các môn thể thao mạo hiểm khác, những lĩnh vực VANS nhắm tới hoàn toàn là thể thao mạo hiểm với những chương trình và cuộc thi hấp dẫn tại US.",
    },
];

